on:
  push:
    branches:
    - master

name: "Build And Push Docker"

jobs:
  build-and-push-docker:
    name: "Build And Push Docker"

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Install dependencies"
      run: docker-compose run --rm yarn yarn install

    - name: "Build event-engine-cockpit"
      run: docker-compose run --rm yarn yarn build

    - name: "Build image"
      run: docker-compose build event-engine-cockpit

    - name: "Login github package registry"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: docker login -u $DOCKER_USERNAME -p "$DOCKER_TOKEN"

    - name: "Tag image"
      run: "docker tag $(docker images | grep -E '^cockpit_event-engine-cockpit.*latest' | awk -e '{print $3}') docker.pkg.github.com/event-engine/cockpit/event-engine-cockpit:$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"

    - name: "Push image"
      run: "docker push proophsoftware/event-engine-cockpit:$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"

    - name: "Cleanup"
      run: rm /home/runner/.docker/config.json

